### ISSUE TITLE
"Very simple" compilation

### ISSUE THREAD

**Issue by HorvathAkosPeter** [martinmroz/lemon#5]
The doc states:

"
      This is a very simple calulator. To compile the
      example do the following:

         $ make"

How is it possible, this directory doesn't even have a Makefile!

**Comment by gonzus** [comment]
I just submitted https://github.com/martinmroz/lemon/pull/6 which fixes this problem.

**Comment by HorvathAkosPeter** [comment]
Thank you very much! Lemon is imho a very, very nice thing.

**Comment by gonzus** [comment]
I am not sure the repo owner is actually around and/or is taking PRs...  :-(
